version: "3.9"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
    - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0"
    volumes:
    - "./:/srv"
    depends_on:
      - redis

  celery:
    build: .
    volumes:
      - "./:/srv"
    depends_on:
      - redis
    command: "celery --app app.worker worker --loglevel=info"